[metadata]
version = 1
generated_at = "2026-01-26T07:42:02.150546+00:00"

[[dependency]]
name = "stream-echo-server-python"
actr_type = "acme+StreamEchoServer"
fingerprint = "service_semantic:8cd6382d374752af9f3ad1488cb4d465dd0fc1a8e22b69eee6e5a75d793d0708"
cached_at = "2026-01-26T07:42:02.150545+00:00"

[[dependency.files]]
path = "stream-echo-server-python/stream_server.proto"
fingerprint = ""
