[metadata]
version = 1
generated_at = "2026-01-30T10:10:12.902418+00:00"

[[dependency]]
name = "data-stream-peer-concurrent-server-python"
actr_type = "acme+DataStreamConcurrentServer"
fingerprint = "service_semantic:10eb4e7249407dbad9b9b00add8a736eac8c5a106dfee2fa2d904defb088672e"
cached_at = "2026-01-30T10:10:12.902416+00:00"

[[dependency.files]]
path = "data-stream-peer-concurrent-server-python/data_stream_peer.proto"
fingerprint = ""
