[metadata]
version = 1
generated_at = "2026-01-14T05:17:27.774650+00:00"

[[dependency]]
name = "stream-register-server-python"
actr_type = "acme+StreamRegisterServer"
fingerprint = "service_semantic:bd6459e66bdf2ff6d25f1dfd554d207a2e330b72a72c414014dde82097bbe29e"
cached_at = "2026-01-14T05:17:27.774646+00:00"

[[dependency.files]]
path = "stream-register-server-python/stream_server.proto"
fingerprint = ""
